// Shared similar-sounding pairs data
const SIMILAR_PAIRS = [
      {arabic1:"يوم",translit1:"Yawm",meaning1:"Day",freq1:475,arabic2:"نوم",translit2:"Nawm",meaning2:"Sleep",freq2:4,category:"One-Letter Swap"},
      {arabic1:"ناس",translit1:"Naas",meaning1:"Mankind / people",freq1:124,arabic2:"نفس",translit2:"Nafs",meaning2:"Soul",freq2:295,category:"One-Letter Swap"},
      {arabic1:"نفس",translit1:"Nafs",meaning1:"Soul",freq1:295,arabic2:"نفع",translit2:"Naf'",meaning2:"Benefit",freq2:31,category:"Letter Added/Removed"},
      {arabic1:"عبد",translit1:"Abd",meaning1:"Servant / slave",freq1:135,arabic2:"أب",translit2:"Ab",meaning2:"Father",freq2:117,category:"Letter Added/Removed"},
      {arabic1:"أرض",translit1:"Ard",meaning1:"Earth",freq1:81,arabic2:"عبد",translit2:"Abd",meaning2:"Servant / slave",freq2:135,category:"One-Letter Swap"},
      {arabic1:"جاء",translit1:"Jaa'a",meaning1:"He came",freq1:105,arabic2:"جعل",translit2:"Ja'ala",meaning2:"He made / appointed",freq2:92,category:"Letter Added/Removed"},
      {arabic1:"بل",translit1:"Bal",meaning1:"Rather / but",freq1:128,arabic2:"بعض",translit2:"Ba'd",meaning2:"Some / part",freq2:52,category:"One-Letter Swap"},
      {arabic1:"ناس",translit1:"Naas",meaning1:"Mankind / people",freq1:124,arabic2:"نار",translit2:"Naar",meaning2:"Fire / Hellfire",freq2:52,category:"One-Letter Swap"},
      {arabic1:"عقل",translit1:"Aql",meaning1:"Intellect",freq1:49,arabic2:"أهل",translit2:"Ahl",meaning2:"People / Family",freq2:127,category:"One-Letter Swap"},
      {arabic1:"بعض",translit1:"Ba'd",meaning1:"Some / part",freq1:52,arabic2:"يد",translit2:"Yad",meaning2:"Hand",freq2:120,category:"One-Letter Swap"},
      {arabic1:"عبد",translit1:"Abd",meaning1:"Servant / slave",freq1:135,arabic2:"عهد",translit2:"Ahd",meaning2:"Covenant",freq2:29,category:"One-Letter Swap"},
      {arabic1:"عبد",translit1:"Abd",meaning1:"Servant / slave",freq1:135,arabic2:"أبد",translit2:"Abad",meaning2:"Forever",freq2:28,category:"Letter Added/Removed"},
      {arabic1:"بين",translit1:"Bayn",meaning1:"Between",freq1:92,arabic2:"بيت",translit2:"Bayt",meaning2:"House",freq2:64,category:"One-Letter Swap"},
      {arabic1:"عهد",translit1:"Ahd",meaning1:"Covenant",freq1:29,arabic2:"أهل",translit2:"Ahl",meaning2:"People / Family",freq2:127,category:"One-Letter Swap"},
      {arabic1:"بل",translit1:"Bal",meaning1:"Rather / but",freq1:128,arabic2:"آل",translit2:"Aal",meaning2:"Family",freq2:26,category:"One-Letter Swap"},
      {arabic1:"آل",translit1:"Aal",meaning1:"Family",freq1:26,arabic2:"أهل",translit2:"Ahl",meaning2:"People / Family",freq2:127,category:"One-Letter Swap"},
      {arabic1:"جهل",translit1:"Jahl",meaning1:"Ignorance",freq1:24,arabic2:"أهل",translit2:"Ahl",meaning2:"People / Family",freq2:127,category:"Letter Added/Removed"},
      {arabic1:"بل",translit1:"Bal",meaning1:"Rather / but",freq1:128,arabic2:"بأس",translit2:"Ba's",meaning2:"Might / Hardship",freq2:18,category:"One-Letter Swap"},
      {arabic1:"عدل",translit1:"Adl",meaning1:"Justice",freq1:14,arabic2:"أهل",translit2:"Ahl",meaning2:"People / Family",freq2:127,category:"One-Letter Swap"},
      {arabic1:"بين",translit1:"Bayn",meaning1:"Between",freq1:92,arabic2:"عين",translit2:"Ayn",meaning2:"Eye / Spring",freq2:47,category:"Letter Added/Removed"},
      {arabic1:"قلب",translit1:"Qalb",meaning1:"Heart",freq1:132,arabic2:"كلب",translit2:"Kalb",meaning2:"Dog",freq2:5,category:"One-Letter Swap"},
      {arabic1:"بل",translit1:"Bal",meaning1:"Rather / but",freq1:128,arabic2:"بيع",translit2:"Bay'",meaning2:"Trade / Selling",freq2:7,category:"One-Letter Swap"},
      {arabic1:"صلاة",translit1:"Salaah",meaning1:"Prayer",freq1:83,arabic2:"ساعة",translit2:"Saa'ah",meaning2:"Hour",freq2:48,category:"Letter Added/Removed"},
      {arabic1:"قول",translit1:"Qawl",meaning1:"Saying / word / statement",freq1:75,arabic2:"قتل",translit2:"Qatl",meaning2:"Killing / Murder",freq2:53,category:"One-Letter Swap"},
      {arabic1:"نحل",translit1:"Nahl",meaning1:"Bee",freq1:1,arabic2:"أهل",translit2:"Ahl",meaning2:"People / Family",freq2:127,category:"Letter Added/Removed"},
      {arabic1:"حين",translit1:"Heen",meaning1:"Time / Moment",freq1:34,arabic2:"دين",translit2:"Deen",meaning2:"Religion / Judgment",freq2:92,category:"One-Letter Swap"},
      {arabic1:"جاء",translit1:"Jaa'a",meaning1:"He came",freq1:105,arabic2:"جمع",translit2:"Jama'a",meaning2:"He gathered",freq2:20,category:"Letter Added/Removed"},
      {arabic1:"ملك",translit1:"Malak",meaning1:"Angel / king",freq1:95,arabic2:"ملإ",translit2:"Mala'",meaning2:"Chiefs / Assembly",freq2:30,category:"Letter Added/Removed"},
      {arabic1:"يد",translit1:"Yad",meaning1:"Hand",freq1:120,arabic2:"رعد",translit2:"Ra'd",meaning2:"Thunder",freq2:2,category:"One-Letter Swap"},
      {arabic1:"أمر",translit1:"Amr",meaning1:"Command / matter",freq1:88,arabic2:"أجر",translit2:"Ajr",meaning2:"Reward / wage",freq2:32,category:"One-Letter Swap"},
      {arabic1:"سلام",translit1:"Salaam",meaning1:"Peace",freq1:36,arabic2:"صلاة",translit2:"Salaah",meaning2:"Prayer",freq2:83,category:"One-Letter Swap"},
      {arabic1:"أب",translit1:"Ab",meaning1:"Father",freq1:117,arabic2:"كعب",translit2:"Ka'b",meaning2:"Ankle",freq2:1,category:"Letter Added/Removed"},
      {arabic1:"بين",translit1:"Bayn",meaning1:"Between",freq1:92,arabic2:"بطن",translit2:"Batn",meaning2:"Belly / Womb",freq2:21,category:"One-Letter Swap"},
      {arabic1:"ولد",translit1:"Walad",meaning1:"Child / Boy",freq1:102,arabic2:"واد",translit2:"Waad",meaning2:"Valley",freq2:9,category:"Letter Added/Removed"},
      {arabic1:"أرض",translit1:"Ard",meaning1:"Earth",freq1:81,arabic2:"عهد",translit2:"Ahd",meaning2:"Covenant",freq2:29,category:"One-Letter Swap"},
      {arabic1:"جاء",translit1:"Jaa'a",meaning1:"He came",freq1:105,arabic2:"جار",translit2:"Jaar",meaning2:"Neighbor",freq2:3,category:"One-Letter Swap"},
      {arabic1:"أمر",translit1:"Amr",meaning1:"Command / matter",freq1:88,arabic2:"أمن",translit2:"Amn",meaning2:"Safety / Security",freq2:19,category:"One-Letter Swap"},
      {arabic1:"ولد",translit1:"Walad",meaning1:"Child / Boy",freq1:102,arabic2:"وتد",translit2:"Watad",meaning2:"Peg / Stake",freq2:3,category:"One-Letter Swap"},
      {arabic1:"طين",translit1:"Teen",meaning1:"Clay",freq1:12,arabic2:"دين",translit2:"Deen",meaning2:"Religion / Judgment",freq2:92,category:"One-Letter Swap"},
      {arabic1:"نار",translit1:"Naar",meaning1:"Fire / Hellfire",freq1:52,arabic2:"دار",translit2:"Daar",meaning2:"Home / Abode",freq2:48,category:"One-Letter Swap"},
      {arabic1:"بين",translit1:"Bayn",meaning1:"Between",freq1:92,arabic2:"بيع",translit2:"Bay'",meaning2:"Trade / Selling",freq2:7,category:"Letter Added/Removed"},
      {arabic1:"أمر",translit1:"Amr",meaning1:"Command / matter",freq1:88,arabic2:"عم",translit2:"Amm",meaning2:"Uncle (paternal)",freq2:5,category:"One-Letter Swap"},
      {arabic1:"ماء",translit1:"Maa'",meaning1:"Water",freq1:63,arabic2:"ملإ",translit2:"Mala'",meaning2:"Chiefs / Assembly",freq2:30,category:"Letter Added/Removed"},
      {arabic1:"أمر",translit1:"Amr",meaning1:"Command / matter",freq1:88,arabic2:"عصر",translit2:"Asr",meaning2:"Afternoon / Time",freq2:1,category:"One-Letter Swap"},
      {arabic1:"دليل",translit1:"Daleel",meaning1:"Proof / guide",freq1:9,arabic2:"قليل",translit2:"Qaleel",meaning2:"Little / Few",freq2:76,category:"One-Letter Swap"},
      {arabic1:"خير",translit1:"Khayr",meaning1:"Good / better",freq1:78,arabic2:"خمر",translit2:"Khamr",meaning2:"Wine / Intoxicants",freq2:6,category:"One-Letter Swap"},
      {arabic1:"صلاة",translit1:"Salaah",meaning1:"Prayer",freq1:83,arabic2:"فلاح",translit2:"Falaah",meaning2:"Success",freq2:1,category:"One-Letter Swap"},
      {arabic1:"خير",translit1:"Khayr",meaning1:"Good / better",freq1:78,arabic2:"خيل",translit2:"Khayl",meaning2:"Horses",freq2:5,category:"One-Letter Swap"},
      {arabic1:"بعض",translit1:"Ba'd",meaning1:"Some / part",freq1:52,arabic2:"أبد",translit2:"Abad",meaning2:"Forever",freq2:28,category:"Letter Added/Removed"},
      {arabic1:"صبر",translit1:"Sabr",meaning1:"Patience / steadfastness",freq1:33,arabic2:"صدر",translit2:"Sadr",meaning2:"Chest",freq2:44,category:"One-Letter Swap"},
      {arabic1:"عقل",translit1:"Aql",meaning1:"Intellect",freq1:49,arabic2:"آل",translit2:"Aal",meaning2:"Family",freq2:26,category:"One-Letter Swap"},
      {arabic1:"بشر",translit1:"Bashar",meaning1:"Human being / mankind",freq1:37,arabic2:"بصر",translit2:"Basar",meaning2:"Sight",freq2:37,category:"Letter Added/Removed"},
      {arabic1:"سبعة",translit1:"Sab'ah",meaning1:"Seven",freq1:24,arabic2:"ساعة",translit2:"Saa'ah",meaning2:"Hour",freq2:48,category:"One-Letter Swap"},
      {arabic1:"بيع",translit1:"Bay'",meaning1:"Trade / Selling",freq1:7,arabic2:"بيت",translit2:"Bayt",meaning2:"House",freq2:64,category:"Letter Added/Removed"},
      {arabic1:"بعض",translit1:"Ba'd",meaning1:"Some / part",freq1:52,arabic2:"بأس",translit2:"Ba's",meaning2:"Might / Hardship",freq2:18,category:"One-Letter Swap"},
      {arabic1:"عجب",translit1:"Ajab",meaning1:"Wonder / Astonishment",freq1:27,arabic2:"أجل",translit2:"Ajal",meaning2:"Term / Deadline",freq2:43,category:"One-Letter Swap"},
      {arabic1:"أجل",translit1:"Ajal",meaning1:"Term / Deadline",freq1:43,arabic2:"آل",translit2:"Aal",meaning2:"Family",freq2:26,category:"Letter Added/Removed"},
      {arabic1:"ماء",translit1:"Maa'",meaning1:"Water",freq1:63,arabic2:"عمى",translit2:"Amaa",meaning2:"Blindness",freq2:4,category:"Letter Added/Removed"},
      {arabic1:"فوز",translit1:"Fawz",meaning1:"Triumph",freq1:16,arabic2:"فوق",translit2:"Fawq",meaning2:"Above / Over",freq2:51,category:"One-Letter Swap"},
      {arabic1:"ساعة",translit1:"Saa'ah",meaning1:"Hour",freq1:48,arabic2:"سنة",translit2:"Sanah",meaning2:"Year",freq2:19,category:"One-Letter Swap"},
      {arabic1:"قدر",translit1:"Qadr",meaning1:"Decree / power / destiny",freq1:22,arabic2:"صدر",translit2:"Sadr",meaning2:"Chest",freq2:44,category:"One-Letter Swap"},
      {arabic1:"عين",translit1:"Ayn",meaning1:"Eye / Spring",freq1:47,arabic2:"أمن",translit2:"Amn",meaning2:"Safety / Security",freq2:19,category:"One-Letter Swap"},
      {arabic1:"بصير",translit1:"Baseer",meaning1:"All-Seeing / seeing",freq1:45,arabic2:"مصير",translit2:"Maseer",meaning2:"Destination / return",freq2:18,category:"One-Letter Swap"},
      {arabic1:"طاعة",translit1:"Taa'ah",meaning1:"Obedience",freq1:15,arabic2:"ساعة",translit2:"Saa'ah",meaning2:"Hour",freq2:48,category:"One-Letter Swap"},
      {arabic1:"طاعة",translit1:"Taa'ah",meaning1:"Obedience",freq1:15,arabic2:"طعام",translit2:"Ta'aam",meaning2:"Food",freq2:48,category:"One-Letter Swap"},
      {arabic1:"عدل",translit1:"Adl",meaning1:"Justice",freq1:14,arabic2:"عقل",translit2:"Aql",meaning2:"Intellect",freq2:49,category:"One-Letter Swap"},
      {arabic1:"شر",translit1:"Sharr",meaning1:"Evil / harm",freq1:41,arabic2:"شهر",translit2:"Shahr",meaning2:"Month",freq2:21,category:"One-Letter Swap"},
      {arabic1:"دعوا",translit1:"Da'aw",meaning1:"They called / invited",freq1:14,arabic2:"دار",translit2:"Daar",meaning2:"Home / Abode",freq2:48,category:"One-Letter Swap"},
      {arabic1:"سلام",translit1:"Salaam",meaning1:"Peace",freq1:36,arabic2:"ظلام",translit2:"Zalaam",meaning2:"Darkness",freq2:23,category:"One-Letter Swap"},
      {arabic1:"بعض",translit1:"Ba'd",meaning1:"Some / part",freq1:52,arabic2:"بيع",translit2:"Bay'",meaning2:"Trade / Selling",freq2:7,category:"One-Letter Swap"},
      {arabic1:"شر",translit1:"Sharr",meaning1:"Evil / harm",freq1:41,arabic2:"شرق",translit2:"Sharq",meaning2:"East",freq2:17,category:"One-Letter Swap"},
      {arabic1:"بصير",translit1:"Baseer",meaning1:"All-Seeing / seeing",freq1:45,arabic2:"بشير",translit2:"Basheer",meaning2:"Bringer of glad tidings",freq2:12,category:"Letter Added/Removed"},
      {arabic1:"بعض",translit1:"Ba'd",meaning1:"Some / part",freq1:52,arabic2:"بعل",translit2:"Ba'l",meaning2:"Husband",freq2:4,category:"One-Letter Swap"},
      {arabic1:"سمع",translit1:"Sam'",meaning1:"Hearing",freq1:42,arabic2:"سعي",translit2:"Sa'y",meaning2:"Effort / Pursuit",freq2:14,category:"One-Letter Swap"},
      {arabic1:"نار",translit1:"Naar",meaning1:"Fire / Hellfire",freq1:52,arabic2:"جار",translit2:"Jaar",meaning2:"Neighbor",freq2:3,category:"One-Letter Swap"},
      {arabic1:"بعض",translit1:"Ba'd",meaning1:"Some / part",freq1:52,arabic2:"رعد",translit2:"Ra'd",meaning2:"Thunder",freq2:2,category:"One-Letter Swap"},
      {arabic1:"نور",translit1:"Noor",meaning1:"Light",freq1:49,arabic2:"حور",translit2:"Hoor",meaning2:"Houris (Fair companions)",freq2:4,category:"One-Letter Swap"},
      {arabic1:"دم",translit1:"Dam",meaning1:"Blood",freq1:10,arabic2:"سمع",translit2:"Sam'",meaning2:"Hearing",freq2:42,category:"One-Letter Swap"},
      {arabic1:"أمة",translit1:"Ummah",meaning1:"Community / nation",freq1:48,arabic2:"عمرة",translit2:"Umrah",meaning2:"Lesser Pilgrimage",freq2:3,category:"One-Letter Swap"},
      {arabic1:"أمة",translit1:"Ummah",meaning1:"Community / nation",freq1:48,arabic2:"عمة",translit2:"Ammah",meaning2:"Aunt (paternal)",freq2:3,category:"Vowel Shift"},
      {arabic1:"سمع",translit1:"Sam'",meaning1:"Hearing",freq1:42,arabic2:"عام",translit2:"Aam",meaning2:"Year",freq2:9,category:"One-Letter Swap"},
      {arabic1:"جار",translit1:"Jaar",meaning1:"Neighbor",freq1:3,arabic2:"دار",translit2:"Daar",meaning2:"Home / Abode",freq2:48,category:"One-Letter Swap"},
      {arabic1:"دهر",translit1:"Dahr",meaning1:"Time / Eternity",freq1:2,arabic2:"دار",translit2:"Daar",meaning2:"Home / Abode",freq2:48,category:"One-Letter Swap"},
      {arabic1:"بعث",translit1:"Ba'th",meaning1:"He sent / resurrection",freq1:28,arabic2:"بطن",translit2:"Batn",meaning2:"Belly / Womb",freq2:21,category:"One-Letter Swap"},
      {arabic1:"صراط",translit1:"Siraat",meaning1:"Path",freq1:45,arabic2:"سراج",translit2:"Siraaj",meaning2:"Lamp",freq2:4,category:"One-Letter Swap"},
      {arabic1:"حياة",translit1:"Hayaat",meaning1:"Life",freq1:46,arabic2:"حياء",translit2:"Hayaa'",meaning2:"Shyness / Modesty",freq2:1,category:"Letter Added/Removed"},
      {arabic1:"يقين",translit1:"Yaqeen",meaning1:"Certainty",freq1:8,arabic2:"يمين",translit2:"Yameen",meaning2:"Right hand / Right",freq2:39,category:"One-Letter Swap"},
      {arabic1:"بحر",translit1:"Bahr",meaning1:"Sea / ocean",freq1:33,arabic2:"ظهر",translit2:"Zahr",meaning2:"Back",freq2:14,category:"One-Letter Swap"},
      {arabic1:"بحر",translit1:"Bahr",meaning1:"Sea / ocean",freq1:33,arabic2:"جهر",translit2:"Jahr",meaning2:"Public / Loud",freq2:14,category:"One-Letter Swap"},
      {arabic1:"طين",translit1:"Teen",meaning1:"Clay",freq1:12,arabic2:"حين",translit2:"Heen",meaning2:"Time / Moment",freq2:34,category:"One-Letter Swap"},
      {arabic1:"صدر",translit1:"Sadr",meaning1:"Chest",freq1:44,arabic2:"سدر",translit2:"Sidr",meaning2:"Lote tree",freq2:2,category:"Vowel Shift"},
      {arabic1:"سوق",translit1:"Sooq",meaning1:"Market",freq1:3,arabic2:"سوء",translit2:"Soo'",meaning2:"Evil / Harm",freq2:43,category:"Letter Added/Removed"},
      {arabic1:"شر",translit1:"Sharr",meaning1:"Evil / harm",freq1:41,arabic2:"ذرة",translit2:"Dharr",meaning2:"Atom / Speck",freq2:4,category:"One-Letter Swap"},
      {arabic1:"أمل",translit1:"Amal",meaning1:"Hope",freq1:2,arabic2:"أجل",translit2:"Ajal",meaning2:"Term / Deadline",freq2:43,category:"One-Letter Swap"},
      {arabic1:"حمد",translit1:"Hamd",meaning1:"Praise",freq1:43,arabic2:"حوض",translit2:"Hawd",meaning2:"Pool / Basin",freq2:1,category:"One-Letter Swap"},
      {arabic1:"شر",translit1:"Sharr",meaning1:"Evil / harm",freq1:41,arabic2:"حر",translit2:"Harr",meaning2:"Heat",freq2:3,category:"Letter Added/Removed"},
      {arabic1:"عسل",translit1:"Asal",meaning1:"Honey",freq1:1,arabic2:"أجل",translit2:"Ajal",meaning2:"Term / Deadline",freq2:43,category:"One-Letter Swap"},
      {arabic1:"حكيم",translit1:"Hakeem",meaning1:"All-Wise / wise",freq1:38,arabic2:"حميم",translit2:"Hameem",meaning2:"Scalding water",freq2:5,category:"One-Letter Swap"},
      {arabic1:"شر",translit1:"Sharr",meaning1:"Evil / harm",freq1:41,arabic2:"شعر",translit2:"Sha'r",meaning2:"Hair",freq2:2,category:"Letter Added/Removed"},
      {arabic1:"موت",translit1:"Mawt",meaning1:"Death",freq1:42,arabic2:"سوط",translit2:"Sawt",meaning2:"Whip / Scourge",freq2:1,category:"One-Letter Swap"},
      {arabic1:"سبعة",translit1:"Sab'ah",meaning1:"Seven",freq1:24,arabic2:"سنة",translit2:"Sanah",meaning2:"Year",freq2:19,category:"One-Letter Swap"},
      {arabic1:"تحت",translit1:"Taht",meaning1:"Beneath / Under",freq1:40,arabic2:"رهط",translit2:"Raht",meaning2:"Group of men",freq2:3,category:"One-Letter Swap"},
      {arabic1:"مطر",translit1:"Matar",meaning1:"Rain",freq1:9,arabic2:"متاع",translit2:"Mataa'",meaning2:"Provision / Equipment",freq2:33,category:"One-Letter Swap"},
      {arabic1:"شجر",translit1:"Shajar",meaning1:"Tree",freq1:26,arabic2:"حجر",translit2:"Hajar",meaning2:"Stone",freq2:14,category:"Letter Added/Removed"},
      {arabic1:"عدل",translit1:"Adl",meaning1:"Justice",freq1:14,arabic2:"آل",translit2:"Aal",meaning2:"Family",freq2:26,category:"One-Letter Swap"},
      {arabic1:"أم",translit1:"Umm",meaning1:"Mother",freq1:35,arabic2:"عم",translit2:"Amm",meaning2:"Uncle (paternal)",freq2:5,category:"Vowel Shift"},
      {arabic1:"رضا",translit1:"Ridaa",meaning1:"Pleasure / satisfaction",freq1:31,arabic2:"ربا",translit2:"Ribaa",meaning2:"Usury / Interest",freq2:8,category:"One-Letter Swap"},
      {arabic1:"فضل",translit1:"Fadl",meaning1:"Bounty / grace",freq1:25,arabic2:"عدل",translit2:"Adl",meaning2:"Justice",freq2:14,category:"Letter Added/Removed"},
      {arabic1:"ليلة",translit1:"Layl",meaning1:"Night",freq1:28,arabic2:"ويل",translit2:"Wayl",meaning2:"Woe / ruin",freq2:11,category:"One-Letter Swap"},
      {arabic1:"فجر",translit1:"Fajr",meaning1:"Dawn / daybreak",freq1:6,arabic2:"أجر",translit2:"Ajr",meaning2:"Reward / wage",freq2:32,category:"Letter Added/Removed"},
      {arabic1:"بصر",translit1:"Basar",meaning1:"Sight",freq1:37,arabic2:"بصل",translit2:"Basal",meaning2:"Onion",freq2:1,category:"One-Letter Swap"},
      {arabic1:"جهر",translit1:"Jahr",meaning1:"Public / Loud",freq1:14,arabic2:"جهل",translit2:"Jahl",meaning2:"Ignorance",freq2:24,category:"One-Letter Swap"},
      {arabic1:"ليلة",translit1:"Layl",meaning1:"Night",freq1:28,arabic2:"كيل",translit2:"Kayl",meaning2:"Measure",freq2:9,category:"One-Letter Swap"},
      {arabic1:"ضعف",translit1:"Da'f",meaning1:"Weakness",freq1:6,arabic2:"نفع",translit2:"Naf'",meaning2:"Benefit",freq2:31,category:"One-Letter Swap"},
      {arabic1:"وضع",translit1:"Wada'a",meaning1:"He placed / put down",freq1:12,arabic2:"وراء",translit2:"Waraa'",meaning2:"Behind / Beyond",freq2:24,category:"One-Letter Swap"},
      {arabic1:"بحر",translit1:"Bahr",meaning1:"Sea / ocean",freq1:33,arabic2:"دهر",translit2:"Dahr",meaning2:"Time / Eternity",freq2:2,category:"One-Letter Swap"},
      {arabic1:"عام",translit1:"Aam",meaning1:"Year",freq1:9,arabic2:"آل",translit2:"Aal",meaning2:"Family",freq2:26,category:"One-Letter Swap"},
      {arabic1:"أبد",translit1:"Abad",meaning1:"Forever",freq1:28,arabic2:"أبيض",translit2:"Abyad",meaning2:"White",freq2:7,category:"Letter Added/Removed"},
      {arabic1:"رأس",translit1:"Ra's",meaning1:"Head",freq1:17,arabic2:"بأس",translit2:"Ba's",meaning2:"Might / Hardship",freq2:18,category:"One-Letter Swap"},
      {arabic1:"بعث",translit1:"Ba'th",meaning1:"He sent / resurrection",freq1:28,arabic2:"فتح",translit2:"Fath",meaning2:"Victory / conquest",freq2:6,category:"One-Letter Swap"},
      {arabic1:"دعاء",translit1:"Du'aa",meaning1:"Supplication / prayer",freq1:28,arabic2:"ضحى",translit2:"Duhaa",meaning2:"Morning brightness",freq2:6,category:"Letter Added/Removed"},
      {arabic1:"أجر",translit1:"Ajr",meaning1:"Reward / wage",freq1:32,arabic2:"عصر",translit2:"Asr",meaning2:"Afternoon / Time",freq2:1,category:"One-Letter Swap"},
      {arabic1:"عهد",translit1:"Ahd",meaning1:"Covenant",freq1:29,arabic2:"مهد",translit2:"Mahd",meaning2:"Cradle",freq2:4,category:"Letter Added/Removed"},
      {arabic1:"غيب",translit1:"Ghayb",meaning1:"The unseen",freq1:15,arabic2:"غرب",translit2:"Gharb",meaning2:"West",freq2:17,category:"One-Letter Swap"},
      {arabic1:"طريق",translit1:"Tareeq",meaning1:"Way / path",freq1:26,arabic2:"حريق",translit2:"Hareeq",meaning2:"Burning fire",freq2:5,category:"One-Letter Swap"},
      {arabic1:"صدق",translit1:"Sidq",meaning1:"Truth / sincerity",freq1:28,arabic2:"سدر",translit2:"Sidr",meaning2:"Lote tree",freq2:2,category:"One-Letter Swap"},
      {arabic1:"أبد",translit1:"Abad",meaning1:"Forever",freq1:28,arabic2:"عمد",translit2:"Amad",meaning2:"Pillars",freq2:2,category:"One-Letter Swap"},
      {arabic1:"بعل",translit1:"Ba'l",meaning1:"Husband",freq1:4,arabic2:"آل",translit2:"Aal",meaning2:"Family",freq2:26,category:"One-Letter Swap"},
      {arabic1:"أبد",translit1:"Abad",meaning1:"Forever",freq1:28,arabic2:"كبد",translit2:"Kabad",meaning2:"Hardship",freq2:1,category:"Letter Added/Removed"},
      {arabic1:"ظهر",translit1:"Zahr",meaning1:"Back",freq1:14,arabic2:"جهر",translit2:"Jahr",meaning2:"Public / Loud",freq2:14,category:"One-Letter Swap"},
      {arabic1:"ظهر",translit1:"Zahr",meaning1:"Back",freq1:14,arabic2:"زرع",translit2:"Zar'",meaning2:"Crop / Seed",freq2:14,category:"Letter Added/Removed"},
      {arabic1:"أمل",translit1:"Amal",meaning1:"Hope",freq1:2,arabic2:"آل",translit2:"Aal",meaning2:"Family",freq2:26,category:"Letter Added/Removed"},
      {arabic1:"ثمار",translit1:"Thimaar",meaning1:"Fruits",freq1:22,arabic2:"حمار",translit2:"Himaar",meaning2:"Donkey",freq2:5,category:"Letter Added/Removed"},
      {arabic1:"وراء",translit1:"Waraa'",meaning1:"Behind / Beyond",freq1:24,arabic2:"ورق",translit2:"Waraq",meaning2:"Leaf",freq2:3,category:"One-Letter Swap"},
      {arabic1:"عسل",translit1:"Asal",meaning1:"Honey",freq1:1,arabic2:"آل",translit2:"Aal",meaning2:"Family",freq2:26,category:"Letter Added/Removed"},
      {arabic1:"جمع",translit1:"Jama'a",meaning1:"He gathered",freq1:20,arabic2:"جمال",translit2:"Jamaal",meaning2:"Beauty",freq2:5,category:"Letter Added/Removed"},
      {arabic1:"وضع",translit1:"Wada'a",meaning1:"He placed / put down",freq1:12,arabic2:"أعداء",translit2:"A'daa'",meaning2:"Enemies",freq2:13,category:"Letter Added/Removed"},
      {arabic1:"نحل",translit1:"Nahl",meaning1:"Bee",freq1:1,arabic2:"جهل",translit2:"Jahl",meaning2:"Ignorance",freq2:24,category:"One-Letter Swap"},
      {arabic1:"أكواب",translit1:"Akwaab",meaning1:"Cups",freq1:4,arabic2:"أبواب",translit2:"Abwaab",meaning2:"Doors / Gates",freq2:21,category:"One-Letter Swap"},
      {arabic1:"بيع",translit1:"Bay'",meaning1:"Trade / Selling",freq1:7,arabic2:"بأس",translit2:"Ba's",meaning2:"Might / Hardship",freq2:18,category:"One-Letter Swap"},
      {arabic1:"أعداء",translit1:"A'daa'",meaning1:"Enemies",freq1:13,arabic2:"عصا",translit2:"Asaa",meaning2:"Staff",freq2:12,category:"One-Letter Swap"},
      {arabic1:"جمع",translit1:"Jama'a",meaning1:"He gathered",freq1:20,arabic2:"عمى",translit2:"Amaa",meaning2:"Blindness",freq2:4,category:"Letter Added/Removed"},
      {arabic1:"لعنة",translit1:"La'nah",meaning1:"Curse / condemnation",freq1:5,arabic2:"سنة",translit2:"Sanah",meaning2:"Year",freq2:19,category:"One-Letter Swap"},
      {arabic1:"كأس",translit1:"Ka's",meaning1:"Cup / Goblet",freq1:6,arabic2:"بأس",translit2:"Ba's",meaning2:"Might / Hardship",freq2:18,category:"One-Letter Swap"},
      {arabic1:"أمن",translit1:"Amn",meaning1:"Safety / Security",freq1:19,arabic2:"عم",translit2:"Amm",meaning2:"Uncle (paternal)",freq2:5,category:"One-Letter Swap"},
      {arabic1:"عظم",translit1:"Azm",meaning1:"Bone",freq1:14,arabic2:"عام",translit2:"Aam",meaning2:"Year",freq2:9,category:"One-Letter Swap"},
      {arabic1:"شهر",translit1:"Shahr",meaning1:"Month",freq1:21,arabic2:"شعر",translit2:"Sha'r",meaning2:"Hair",freq2:2,category:"Letter Added/Removed"},
      {arabic1:"كأس",translit1:"Ka's",meaning1:"Cup / Goblet",freq1:6,arabic2:"رأس",translit2:"Ra's",meaning2:"Head",freq2:17,category:"One-Letter Swap"},
      {arabic1:"سر",translit1:"Sirr",meaning1:"Secret",freq1:21,arabic2:"سدر",translit2:"Sidr",meaning2:"Lote tree",freq2:2,category:"One-Letter Swap"},
      {arabic1:"سر",translit1:"Sirr",meaning1:"Secret",freq1:21,arabic2:"صهر",translit2:"Sihr",meaning2:"Marriage relationship / In-law",freq2:1,category:"One-Letter Swap"},
      {arabic1:"بأس",translit1:"Ba's",meaning1:"Might / Hardship",freq1:18,arabic2:"بعل",translit2:"Ba'l",meaning2:"Husband",freq2:4,category:"One-Letter Swap"},
      {arabic1:"نخل",translit1:"Nakhl",meaning1:"Date palm",freq1:20,arabic2:"نحل",translit2:"Nahl",meaning2:"Bee",freq2:1,category:"Letter Added/Removed"},
      {arabic1:"بيع",translit1:"Bay'",meaning1:"Trade / Selling",freq1:7,arabic2:"سعي",translit2:"Sa'y",meaning2:"Effort / Pursuit",freq2:14,category:"One-Letter Swap"},
      {arabic1:"ويل",translit1:"Wayl",meaning1:"Woe / ruin",freq1:11,arabic2:"كيل",translit2:"Kayl",meaning2:"Measure",freq2:9,category:"One-Letter Swap"},
      {arabic1:"سعير",translit1:"Sa'eer",meaning1:"Blaze",freq1:16,arabic2:"صعيد",translit2:"Sa'eed",meaning2:"Earth / Soil",freq2:4,category:"One-Letter Swap"},
      {arabic1:"قرين",translit1:"Qareen",meaning1:"Companion / associate",freq1:3,arabic2:"قريب",translit2:"Qareeb",meaning2:"Near / Close",freq2:16,category:"One-Letter Swap"},
      {arabic1:"دم",translit1:"Dam",meaning1:"Blood",freq1:10,arabic2:"عام",translit2:"Aam",meaning2:"Year",freq2:9,category:"One-Letter Swap"},
      {arabic1:"عظم",translit1:"Azm",meaning1:"Bone",freq1:14,arabic2:"عم",translit2:"Amm",meaning2:"Uncle (paternal)",freq2:5,category:"One-Letter Swap"},
      {arabic1:"شرق",translit1:"Sharq",meaning1:"East",freq1:17,arabic2:"شعر",translit2:"Sha'r",meaning2:"Hair",freq2:2,category:"Letter Added/Removed"},
      {arabic1:"رأس",translit1:"Ra's",meaning1:"Head",freq1:17,arabic2:"رعد",translit2:"Ra'd",meaning2:"Thunder",freq2:2,category:"One-Letter Swap"},
      {arabic1:"تبارك",translit1:"Tabaarak",meaning1:"Blessed / exalted",freq1:12,arabic2:"تبار",translit2:"Tabaara",meaning2:"Perished / destroyed",freq2:6,category:"Letter Added/Removed"},
      {arabic1:"يسر",translit1:"Yusr",meaning1:"Ease",freq1:6,arabic2:"عسر",translit2:"Usr",meaning2:"Hardship",freq2:12,category:"Letter Added/Removed"},
      {arabic1:"نجم",translit1:"Najm",meaning1:"Star",freq1:13,arabic2:"نوم",translit2:"Nawm",meaning2:"Sleep",freq2:4,category:"One-Letter Swap"},
      {arabic1:"عمى",translit1:"Amaa",meaning1:"Blindness",freq1:4,arabic2:"أعداء",translit2:"A'daa'",meaning2:"Enemies",freq2:13,category:"One-Letter Swap"},
      {arabic1:"مائة",translit1:"Mi'ah",meaning1:"Hundred",freq1:6,arabic2:"فئة",translit2:"Fi'ah",meaning2:"Group / Company",freq2:11,category:"One-Letter Swap"},
      {arabic1:"ذراع",translit1:"Dhiraa'",meaning1:"Arm / Cubit",freq1:3,arabic2:"ذكرى",translit2:"Dhikraa",meaning2:"Reminder / Remembrance",freq2:14,category:"Letter Added/Removed"},
      {arabic1:"جهر",translit1:"Jahr",meaning1:"Public / Loud",freq1:14,arabic2:"جار",translit2:"Jaar",meaning2:"Neighbor",freq2:3,category:"One-Letter Swap"},
      {arabic1:"فاتحة",translit1:"Faatihah",meaning1:"The Opening",freq1:2,arabic2:"فاكهة",translit2:"Faakihah",meaning2:"Fruit",freq2:14,category:"One-Letter Swap"},
      {arabic1:"ضعف",translit1:"Da'f",meaning1:"Weakness",freq1:6,arabic2:"دم",translit2:"Dam",meaning2:"Blood",freq2:10,category:"One-Letter Swap"},
      {arabic1:"عمى",translit1:"Amaa",meaning1:"Blindness",freq1:4,arabic2:"عصا",translit2:"Asaa",meaning2:"Staff",freq2:12,category:"One-Letter Swap"},
      {arabic1:"ظهر",translit1:"Zahr",meaning1:"Back",freq1:14,arabic2:"دهر",translit2:"Dahr",meaning2:"Time / Eternity",freq2:2,category:"One-Letter Swap"},
      {arabic1:"دهر",translit1:"Dahr",meaning1:"Time / Eternity",freq1:2,arabic2:"جهر",translit2:"Jahr",meaning2:"Public / Loud",freq2:14,category:"One-Letter Swap"},
      {arabic1:"بعيد",translit1:"Ba'eed",meaning1:"Far / Distant",freq1:12,arabic2:"وعيد",translit2:"Wa'eed",meaning2:"Threat / Warning",freq2:4,category:"One-Letter Swap"},
      {arabic1:"بعيد",translit1:"Ba'eed",meaning1:"Far / Distant",freq1:12,arabic2:"صعيد",translit2:"Sa'eed",meaning2:"Earth / Soil",freq2:4,category:"One-Letter Swap"},
      {arabic1:"سعي",translit1:"Sa'y",meaning1:"Effort / Pursuit",freq1:14,arabic2:"فيء",translit2:"Fay'",meaning2:"Shadow / Shade",freq2:2,category:"One-Letter Swap"},
      {arabic1:"مقامع",translit1:"Maqaami'",meaning1:"Iron maces",freq1:1,arabic2:"مقام",translit2:"Maqaam",meaning2:"Station / Place",freq2:15,category:"Letter Added/Removed"},
      {arabic1:"صيف",translit1:"Sayf",meaning1:"Summer",freq1:1,arabic2:"سعي",translit2:"Sa'y",meaning2:"Effort / Pursuit",freq2:14,category:"Letter Added/Removed"},
      {arabic1:"عام",translit1:"Aam",meaning1:"Year",freq1:9,arabic2:"عم",translit2:"Amm",meaning2:"Uncle (paternal)",freq2:5,category:"One-Letter Swap"},
      {arabic1:"عدس",translit1:"Adas",meaning1:"Lentils",freq1:1,arabic2:"أعداء",translit2:"A'daa'",meaning2:"Enemies",freq2:13,category:"One-Letter Swap"},
      {arabic1:"خيل",translit1:"Khayl",meaning1:"Horses",freq1:5,arabic2:"كيل",translit2:"Kayl",meaning2:"Measure",freq2:9,category:"Letter Added/Removed"},
      {arabic1:"حلال",translit1:"Halaal",meaning1:"Permissible / lawful",freq1:12,arabic2:"هلاك",translit2:"Halaak",meaning2:"Destruction",freq2:1,category:"One-Letter Swap"},
      {arabic1:"حلال",translit1:"Halaal",meaning1:"Permissible / lawful",freq1:12,arabic2:"هلال",translit2:"Hilaal",meaning2:"Crescent",freq2:1,category:"Vowel Shift"},
      {arabic1:"لحم",translit1:"Lahm",meaning1:"Flesh / Meat",freq1:12,arabic2:"فهم",translit2:"Fahm",meaning2:"Understanding",freq2:1,category:"One-Letter Swap"},
      {arabic1:"عصر",translit1:"Asr",meaning1:"Afternoon / Time",freq1:1,arabic2:"عسر",translit2:"Usr",meaning2:"Hardship",freq2:12,category:"Vowel Shift"},
      {arabic1:"عسل",translit1:"Asal",meaning1:"Honey",freq1:1,arabic2:"عصا",translit2:"Asaa",meaning2:"Staff",freq2:12,category:"One-Letter Swap"},
      {arabic1:"شراب",translit1:"Sharaab",meaning1:"Drink",freq1:11,arabic2:"سراب",translit2:"Saraab",meaning2:"Mirage",freq2:2,category:"Letter Added/Removed"},
      {arabic1:"لوح",translit1:"Lawh",meaning1:"Tablet",freq1:5,arabic2:"لون",translit2:"Lawn",meaning2:"Color",freq2:7,category:"One-Letter Swap"},
      {arabic1:"واد",translit1:"Waad",meaning1:"Valley",freq1:9,arabic2:"وتد",translit2:"Watad",meaning2:"Peg / Stake",freq2:3,category:"Letter Added/Removed"},
      {arabic1:"ضعف",translit1:"Da'f",meaning1:"Weakness",freq1:6,arabic2:"ضيف",translit2:"Dayf",meaning2:"Guest",freq2:5,category:"Letter Added/Removed"},
      {arabic1:"سحاب",translit1:"Sahaab",meaning1:"Cloud",freq1:9,arabic2:"سراب",translit2:"Saraab",meaning2:"Mirage",freq2:2,category:"One-Letter Swap"},
      {arabic1:"بيع",translit1:"Bay'",meaning1:"Trade / Selling",freq1:7,arabic2:"بعل",translit2:"Ba'l",meaning2:"Husband",freq2:4,category:"One-Letter Swap"},
      {arabic1:"سكينة",translit1:"Sakeenah",meaning1:"Peace / Reassurance",freq1:6,arabic2:"سفينة",translit2:"Safeenah",meaning2:"Ship",freq2:4,category:"One-Letter Swap"},
      {arabic1:"بيع",translit1:"Bay'",meaning1:"Trade / Selling",freq1:7,arabic2:"فيء",translit2:"Fay'",meaning2:"Shadow / Shade",freq2:2,category:"One-Letter Swap"},
      {arabic1:"خيل",translit1:"Khayl",meaning1:"Horses",freq1:5,arabic2:"خال",translit2:"Khaal",meaning2:"Uncle (maternal)",freq2:3,category:"One-Letter Swap"},
      {arabic1:"حوت",translit1:"Hoot",meaning1:"Whale / Fish",freq1:4,arabic2:"حور",translit2:"Hoor",meaning2:"Houris (Fair companions)",freq2:4,category:"One-Letter Swap"},
      {arabic1:"حرير",translit1:"Hareer",meaning1:"Silk",freq1:3,arabic2:"حريق",translit2:"Hareeq",meaning2:"Burning fire",freq2:5,category:"One-Letter Swap"},
      {arabic1:"وعيد",translit1:"Wa'eed",meaning1:"Threat / Warning",freq1:4,arabic2:"صعيد",translit2:"Sa'eed",meaning2:"Earth / Soil",freq2:4,category:"One-Letter Swap"},
      {arabic1:"فجر",translit1:"Fajr",meaning1:"Dawn / daybreak",freq1:6,arabic2:"فقر",translit2:"Faqr",meaning2:"Poverty",freq2:1,category:"One-Letter Swap"},
      {arabic1:"حديد",translit1:"Hadeed",meaning1:"Iron",freq1:6,arabic2:"صديد",translit2:"Sadeed",meaning2:"Pus",freq2:1,category:"One-Letter Swap"},
      {arabic1:"كأس",translit1:"Ka's",meaning1:"Cup / Goblet",freq1:6,arabic2:"كعب",translit2:"Ka'b",meaning2:"Ankle",freq2:1,category:"One-Letter Swap"},
      {arabic1:"حر",translit1:"Harr",meaning1:"Heat",freq1:3,arabic2:"ذرة",translit2:"Dharr",meaning2:"Atom / Speck",freq2:4,category:"Letter Added/Removed"},
      {arabic1:"عمى",translit1:"Amaa",meaning1:"Blindness",freq1:4,arabic2:"أمل",translit2:"Amal",meaning2:"Hope",freq2:2,category:"One-Letter Swap"},
      {arabic1:"عمى",translit1:"Amaa",meaning1:"Blindness",freq1:4,arabic2:"عمد",translit2:"Amad",meaning2:"Pillars",freq2:2,category:"One-Letter Swap"},
      {arabic1:"صيف",translit1:"Sayf",meaning1:"Summer",freq1:1,arabic2:"ضيف",translit2:"Dayf",meaning2:"Guest",freq2:5,category:"One-Letter Swap"},
      {arabic1:"كلب",translit1:"Kalb",meaning1:"Dog",freq1:5,arabic2:"كعب",translit2:"Ka'b",meaning2:"Ankle",freq2:1,category:"Letter Added/Removed"},
      {arabic1:"زنا",translit1:"Zinaa",meaning1:"Adultery / Fornication",freq1:2,arabic2:"بناء",translit2:"Binaa'",meaning2:"Building / Canopy",freq2:4,category:"One-Letter Swap"},
      {arabic1:"مجد",translit1:"Majd",meaning1:"Glory",freq1:1,arabic2:"مهد",translit2:"Mahd",meaning2:"Cradle",freq2:4,category:"One-Letter Swap"},
      {arabic1:"عمى",translit1:"Amaa",meaning1:"Blindness",freq1:4,arabic2:"أمام",translit2:"Amaam",meaning2:"Front / Before",freq2:1,category:"Letter Added/Removed"},
      {arabic1:"صيف",translit1:"Sayf",meaning1:"Summer",freq1:1,arabic2:"سقف",translit2:"Saqf",meaning2:"Roof / Ceiling",freq2:4,category:"One-Letter Swap"},
      {arabic1:"صعيد",translit1:"Sa'eed",meaning1:"Earth / Soil",freq1:4,arabic2:"صديد",translit2:"Sadeed",meaning2:"Pus",freq2:1,category:"Letter Added/Removed"},
      {arabic1:"نجاة",translit1:"Najaah",meaning1:"Salvation",freq1:1,arabic2:"نعجة",translit2:"Na'jah",meaning2:"Ewe (female sheep)",freq2:3,category:"Letter Added/Removed"},
      {arabic1:"معاد",translit1:"Ma'aad",meaning1:"Return",freq1:1,arabic2:"مقعد",translit2:"Maq'ad",meaning2:"Seat",freq2:3,category:"One-Letter Swap"},
      {arabic1:"نحل",translit1:"Nahl",meaning1:"Bee",freq1:1,arabic2:"نمل",translit2:"Naml",meaning2:"Ant",freq2:3,category:"One-Letter Swap"},
      {arabic1:"رعد",translit1:"Ra'd",meaning1:"Thunder",freq1:2,arabic2:"روض",translit2:"Rawd",meaning2:"Meadows",freq2:2,category:"Letter Added/Removed"},
      {arabic1:"أمل",translit1:"Amal",meaning1:"Hope",freq1:2,arabic2:"عمد",translit2:"Amad",meaning2:"Pillars",freq2:2,category:"One-Letter Swap"},
      {arabic1:"حر",translit1:"Harr",meaning1:"Heat",freq1:3,arabic2:"حرف",translit2:"Harf",meaning2:"Edge / Letter",freq2:1,category:"One-Letter Swap"},
      {arabic1:"عاقر",translit1:"Aaqir",meaning1:"Barren (woman)",freq1:3,arabic2:"عابر",translit2:"Aabir",meaning2:"Passerby",freq2:1,category:"One-Letter Swap"},
      {arabic1:"حوض",translit1:"Hawd",meaning1:"Pool / Basin",freq1:1,arabic2:"روض",translit2:"Rawd",meaning2:"Meadows",freq2:2,category:"One-Letter Swap"},
      {arabic1:"عسل",translit1:"Asal",meaning1:"Honey",freq1:1,arabic2:"أمل",translit2:"Amal",meaning2:"Hope",freq2:2,category:"One-Letter Swap"},
      {arabic1:"شعر",translit1:"Sha'r",meaning1:"Hair",freq1:2,arabic2:"شعب",translit2:"Sha'b",meaning2:"People / Nation",freq2:1,category:"One-Letter Swap"},
      {arabic1:"حياء",translit1:"Hayaa'",meaning1:"Shyness / Modesty",freq1:1,arabic2:"هباء",translit2:"Habaa'",meaning2:"Dust",freq2:2,category:"One-Letter Swap"},
      {arabic1:"صهر",translit1:"Sihr",meaning1:"Marriage relationship / In-law",freq1:1,arabic2:"سدر",translit2:"Sidr",meaning2:"Lote tree",freq2:2,category:"One-Letter Swap"},
      {arabic1:"عسل",translit1:"Asal",meaning1:"Honey",freq1:1,arabic2:"بصل",translit2:"Basal",meaning2:"Onion",freq2:1,category:"Letter Added/Removed"}
    ];
